### ISSUE TITLE
Please provide the .java files

### ISSUE THREAD

**Issue by abhimuktheeswarar** [marcoscgdev/FABScrollAnimations#1]
Hi @marcoscgdev , I'm looking to implement this for a custom view instead of FAB, so please upload the java files instead of .jar

**Comment by marcoscgdev** [comment]
Hi @abeemukthees thanks for your issue, but I think that it's not necessary at the moment. Best regards.

**Comment by demogorgorn** [comment]
Without java files it's useless lib. There are many analogues

**Comment by marcoscgdev** [comment]
This library has been discontinued. I will probably do a remake (adding java files of course) if I have time.
